### ISSUE TITLE
nassqs_GET returns too many records error with only 69 records!

### ISSUE THREAD

**Issue by rsmiller74** [ropensci/rnassqs#23] opened 2019-12-10 16:38 UTC
Below is a reproduceable example with only 69 records that generates "Request too large error" 

> params <- list("source_desc"="CENSUS", "commodity_desc"="HOGS","agg_level_desc"="COUNTY", "state_alpha"="AK", "year"=1997)
>
> records <- rnassqs::nassqs_record_count(params)   |=========================================| 100% 
> assertthat::assert_that(as.integer(records$count) <= 50000)
[1] TRUE
> records$count 
[1] 69 
>
> raw <- rnassqs::nassqs_GET(params = params, key = api_key)   |=========================================| 100% 
Error: Request was too large. NASS requires that an API call returns a maximum of 50,000 records. Consider subsetting your request by geography or year to reduce the size of your query.
--

**Comment by rsmiller74** [comment] 2019-12-10 16:42
Returns this error for any county with less than 50,000 records.  Same request as above but only changed State to Texas which has 3568 records.


> records$count
[1] 3568
> raw <- rnassqs::nassqs_GET(params = params, key = api_key)   |==========================================| 100%
Error: Request was too large. NASS requires that an API call returns a maximum of 50,000 records. Consider subsetting your request by geography or year to reduce the size of your query.
--

**Comment by econpotter** [comment] 2019-12-10 17:07
@rsmiller74 thank you, I think this is a duplicate of #17 that is the result of a slight change in the function call as a result of the rOpenSci review. If you use

```{r}
params <- list("source_desc"="CENSUS", "commodity_desc"="HOGS","agg_level_desc"="COUNTY", "state_alpha"="AK", "year"=1997)

# works
rnassqs::nassqs(params)

# also works
rnassqs::nassgs_GET(params)

# returns the same error
rnassqs::nassqs_GET(params = params)
```

The big change was `params` no longer should be passed as an argument call, it should just be a list directly. The function `nassqs` now does a check on the list for validity, but `nassqs_GET()` does not, which is how your call gets through without an error that looks like

```{r}
Error in parameter_is_valid(x):
  Parameters 'params' is not a valid parameter. Use `nassqs_params` for a list of valid parameters.
```

I will update so that both functions are clearer. Thanks for filing!

**Comment by rsmiller74** [comment] 2019-12-10 19:32
Thanks for the quick response.  Its working now.  However it also appears that api key is no longer needed in the call (?)

> raw <- rnassqs::nassqs_GET(params, key = api_key)
Error: All components of query must be named

But when I run without the api key then it appears to function.

> raw <- rnassqs::nassqs_GET(params)
  |=================| 100%
> parsed <- rnassqs::nassqs_parse(raw, as = 'data.frame')
> nrow(parsed)
[1] 69

Thanks again.

**Comment by econpotter** [comment] 2019-12-10 20:12
Yep, it automatically looks for the api key stored in the system variable. The new README and docs describe this process but it's a little different than it was. Another change coming from the rOpenSci review. Hopefully it makes it simpler to use, apologies for the non-backward-compatible changes!

I'm going to leave this issue open until I make the error messages more explicit to hopefully make it easier to know what to do if this happens for other folks. Thanks again for filing this.

**Closed as completed** 2020-02-13 20:49 UTC
